import {Dimensions} from 'react-native';
import colors from '../../../../theme/colors';
import {ScaledSheet, vs} from 'react-native-size-matters';
const {width} = Dimensions.get('screen');

export default styles = ScaledSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.BackgroundColor,
  },
  inner: {
    flex: 0.87,
    backgroundColor: colors.BackgroundColor,
  },
  topView: {
    height: '50@vs',
    width: '100%',
    flexDirection: 'row',
    backgroundColor: colors.BackgroundColor,
    elevation: 4,
  },
  Img: {
    flex: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Input: {
    flex: 0.46,
    paddingBottom: 7,
  },
  textInput: {
    height: 58,
    width: '90%',
    borderRadius: 10,
    borderWidth: 0.7,
    alignSelf: 'center',
    flexDirection: 'row',
    borderColor: colors.borderColor,
  },
  tab: {
    height: 42,
    width: '90%',
    borderRadius: 10,
    borderWidth: 0.7,
    alignSelf: 'center',
    flexDirection: 'row',
    borderColor: colors.borderColor,
  },
  listView: {
    height: '80@vs',
    width: '100%',
    flexDirection: 'row',
  },
  bottom: {
    flex: 0.25,
  },
  Text1: {
    fontSize: '17@ms',
    fontWeight: 'bold',
    color: colors.textColor2,
    direction: 'rtl',
  },
  Text2: {
    fontSize: '18@ms',
    fontWeight: 'bold',
    color: colors.textColor2,
    marginRight: '12@s',
  },
  Text3: {
    fontSize: '15@ms',
    color: colors.textColor,
    marginRight: 5,
  },
  Text4: {
    fontSize: '19@ms',
    fontWeight: 'bold',
    color: colors.PrimaryColor,
    paddingRight: '16@s',
    marginTop: '15@vs',
  },
  Text5: {
    fontSize: '16@ms',
    fontWeight: 'bold',
    color: '#E98830',
    marginRight: '10@s',
  },
  Text6: {
    fontSize: '16@ms',
    color: colors.textColor,
    marginRight: '10@s',
  },
  Text7: {
    fontSize: '18@ms',
    color: colors.textColor,
    marginRight: '25@s',
  },
  Text8: {
    fontSize: '18@ms',
    fontWeight: 'bold',
    color: colors.textColor,
    marginRight: '15@s',
  },
  reportText: {
    fontSize: '15@ms',
  },

  button1: {
    height: vs(42),
    width: '94%',
    borderRadius: 8,
    alignSelf: 'center',
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#23973D',
  },
  button01: {
    height: vs(42),
    width: '94%',
    borderRadius: 8,
    alignSelf: 'center',
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.PrimaryColor,
  },
  // button2: {
  //     height: 55,
  //     width: '94%',
  //     borderRadius: 10,
  //     marginTop: '10@vs',
  //     alignSelf: 'center',
  //     elevation: 2,
  //     justifyContent: 'center',
  //     alignItems: 'center',
  //     backgroundColor: colors.PrimaryColor
  // },
  badgeStyle: {
    position: 'absolute',
    top: '0@vs',
    right: '11@s',
  },
  badge: {
    position: 'absolute',
    top: '22@vs',
    right: '-5@s',
  },
  card1: {
    // height: vs(220),
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: '#E6EEF4',
  },
  card2: {
    height: vs(160),
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: '#E6EEF4',
  },
  card3: {
    height: vs(120),
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: '#E6EEF4',
  },
  card4: {
    height: vs(195),
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: '#E6EEF4',
  },
  card5: {
    height: '100@vs',
    borderRadius: 8,
    width: '43%',
    borderWidth: 0.6,
    elevation: 0,
    borderColor: colors.borderColor,
  },
  card6: {
    height: '150@vs',
    borderRadius: 8,
    width: '90%',
    elevation: 4,
    alignSelf: 'center',
    marginTop: '25@vs',
    marginBottom: 5,
  },
  card7: {
    height: '150@vs',
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: '#E6EEF4',
  },
  card8: {
    height: '175@vs',
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: colors.BackgroundColor,
  },
  card9: {
    height: '430@vs',
    marginBottom: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderColor,
    marginTop: '15@vs',
    elevation: 0,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: colors.BackgroundColor,
  },
  card10: {
    height: '100@vs',
    elevation: 2,
    marginBottom: 4,
    borderRadius: 10,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: '#E6EEF4',
  },
  modalBottomView: {
    height: '75@vs',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#fafafa',
    alignSelf: 'flex-end',
    position: 'absolute',
    bottom: '110@vs',
  },

  Avatar: {
    marginTop: '9@vs',
  },

  viewWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: '"rgba(0, 0, 0, 0.6)"',
  },
  modalView: {
    height: '80%',
    marginTop: 100,
    width: width * 1,
    backgroundColor: colors.BackgroundColor,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  verticleLine: {
    height: '80%',
    width: 0.9,
    marginLeft: '25@s',
    backgroundColor: colors.borderColor,
  },
});
